class: "TaskTmall"
module: "asynch"
options:
  login:
    enable: true
    nickname: 'nickname'
    username: 'username'
    password: 'password'
  proxy: true
  storage:
    module: "FileStorage"
    path: ""
  keyword:
    - "大豆"
    - "玉米"