class: "TaskTmall"
module: "async"
options:
  storage:
    module: "FileStorage"
    path: ""
  keyword:
    - "大豆"
    - "玉米"
  proxy: true
  nickname: 'nickname'
  username: 'username'
  password: 'password'