class: "TaskEastmoney"
module: "asynch"
options:
  login:
    enable: false
    nickname: 'nickname'
    username: 'username'
    password: 'password'
  proxy: false
  storage:
    module: "MongoStorage"
    collection: ""
  keyword:
    - "大豆"
